from enum import Enum

class DocumentStatus(Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    PROCESSED = "processed"
    FAILED = "failed"

class FieldType(Enum):
    TEXT = "text"
    SELECT = "select"
    TABLE = "table"
    NUMBER = "number"
    DATE = "date"
    EMAIL = "email"
    CURRENCY = "currency"

class DataType(Enum):
    STRING = "string"
    INTEGER = "integer"
    FLOAT = "float"
    DATE = "date"
    BOOLEAN = "boolean"
    SELECT = "select"

class ExportFormat(Enum):
    PDF = "pdf"
    CSV = "csv"
    EXCEL = "excel"
    JSON = "json"

class FieldName(Enum):
    # Document Identification
    INVOICE_NUMBER = "invoice_number"
    INVOICE_DATE = "invoice_date"
    DUE_DATE = "due_date"
    PO_NUMBER = "po_number"
    CHALLAN_NUMBER = "challan_number"
    CHALLAN_DATE = "challan_date"
    EWAY_BILL_NUMBER = "eway_bill_number"
    EWAY_BILL_DATE = "eway_bill_date"
    BILL_TYPE = "bill_type"
    VOUCHER_TYPE = "voucher_type"
    
    # Parties Involved
    VENDOR_NAME = "vendor_name"
    VENDOR_ADDRESS = "vendor_address"
    VENDOR_GSTIN = "vendor_gstin"
    VENDOR_PAN = "vendor_pan"
    VENDOR_STATE_CODE = "vendor_state_code"
    CUSTOMER_NAME = "customer_name"
    CUSTOMER_ADDRESS = "customer_address"
    CUSTOMER_GSTIN = "customer_gstin"
    CUSTOMER_PAN = "customer_pan"
    CUSTOMER_STATE_CODE = "customer_state_code"
    PLACE_OF_SUPPLY = "place_of_supply"
    SHIP_TO_ADDRESS = "ship_to_address"
    BILLING_ADDRESS = "billing_address"
    
    # Line Items
    ITEM_CODE = "item_code"
    ITEM_DESCRIPTION = "item_description"
    HSN_CODE = "hsn_code"
    SAC_CODE = "sac_code"
    QUANTITY = "quantity"
    UNIT_OF_MEASUREMENT = "unit_of_measurement"
    UNIT_PRICE = "unit_price"
    DISCOUNT_PER_ITEM = "discount_per_item"
    GST_RATE = "gst_rate"
    CGST_RATE = "cgst_rate"
    SGST_RATE = "sgst_rate"
    IGST_RATE = "igst_rate"
    CESS_RATE = "cess_rate"
    TAXABLE_VALUE = "taxable_value"
    CGST_AMOUNT = "cgst_amount"
    SGST_AMOUNT = "sgst_amount"
    IGST_AMOUNT = "igst_amount"
    CESS_AMOUNT = "cess_amount"
    LINE_TOTAL = "line_total"
    
    # Totals & Summary
    SUBTOTAL = "subtotal"
    TOTAL_DISCOUNT = "total_discount"
    TOTAL_TAXABLE_VALUE = "total_taxable_value"
    TOTAL_CGST = "total_cgst"
    TOTAL_SGST = "total_sgst"
    TOTAL_IGST = "total_igst"
    TOTAL_CESS = "total_cess"
    ROUND_OFF_AMOUNT = "round_off_amount"
    TOTAL_AMOUNT = "total_amount"
    AMOUNT_IN_WORDS = "amount_in_words"
    CURRENCY = "currency"
    EXCHANGE_RATE = "exchange_rate"
    TDS_RATE = "tds_rate"
    TDS_AMOUNT = "tds_amount"
    TAX_AMOUNT = "tax_amount"  # Keep existing field for backward compatibility
    
    # Terms & Metadata
    TERMS_AND_CONDITIONS = "terms_and_conditions"
    PAYMENT_TERMS = "payment_terms"
    BANK_ACCOUNT_NUMBER = "bank_account_number"
    IFSC_CODE = "ifsc_code"
    UPI_ID = "upi_id"
    PAYMENT_STATUS = "payment_status"
    PAYMENT_MODE = "payment_mode"
    DELIVERY_TERMS = "delivery_terms"
    DISPATCH_THROUGH = "dispatch_through"
    LR_NUMBER = "lr_number"
    TRANSPORT_MODE = "transport_mode"
    VEHICLE_NUMBER = "vehicle_number"
    
    # Other Useful Fields
    REMARKS = "remarks"
    PREPARED_BY = "prepared_by"
    APPROVED_BY = "approved_by"
    REVERSE_CHARGE = "reverse_charge"
    IS_EXPORT = "is_export"
    IS_COMPOSITE_SUPPLY = "is_composite_supply"
    SUPPLY_TYPE = "supply_type"
    VOUCHER_REFERENCE = "voucher_reference"
    BRANCH_CODE = "branch_code"
    WAREHOUSE_CODE = "warehouse_code" 